### ISSUE TITLE
what does  clip_percentile means when processimgs?

### ISSUE THREAD

**Issue by yt605155624** [hienpham15/CNN_model_ColorConstancy#4]
How to find this value in datasets?

**Comment by yt605155624** [comment]
why clip_percentile !=0.0???

**Comment by hienpham15** [comment]
Its purpose is only to improve the images brightness and contrast. This [is](http://files.is.tue.mpg.de/pgehler/projects/color/index.html) what true images look like after white balancing, and I suppose these images look familiar with your images (in which clip_percentile = 0).

**Comment by yt605155624** [comment]
@hienpham15  will use clip_percentile  break the training data??,and is clip_percentile  just a number you write randomly..(not too big but randomly?)

**Comment by hienpham15** [comment]
Since we are dealing with Color-constancy problem, the answer is no. In fact, we are only interested in which color the images are casted (hence we can white-balance them using the ratio between 3 color channel i.e von Kries ratio).
The clip_percentile is only a mean for you to exclude a percentage of black level in pixel (in this case: 2.5%), you can choose the value bewteen 0%(too dark)-5%(too bright). It's only a mean for displaying images.
To address your concerns, let's put it like this: if your images are dark and color-casted, after white-balancing, they are still dark but the color-casted is removed. 
About the training, if you have doubts, you can try to train without clip_percentile, I don't think the results will be different
